services:
  mongo:
    image: mongo:7
    container_name: sth-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: sth-redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5
    container_name: sth-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password

volumes:
  mongo_data: